[build]
    functions = "./functions"

[[redirects]]
    from = "/api/hello"
    to = "/.netlify/functions/hello"
    status = 200

[[redirects]]
    from = "/api/basic"
    to = "/.netlify/functions/basicApi"
    status = 200